exports.date = {
	'1/1': 'january 1',
	'1/2': 'jan 2',
	'1/3': 'jan 3',
	'1/4': 'jan 4',
	'2/1': 'feb 1',
};

exports.math = {
		0: '0 is the additive identity.',
		1: '1 is the multiplicative identity.',
		2: '2 is the only even prime.',
		3: '3 is the number of spatial dimensions we live in.',
		4: '4 is the smallest number of colors sufficient to color all planar maps.',
		5: '5 is the number of Platonic solids.',
		6: '6 is the smallest perfect number.',
		7: '7 is the smallest number of sides of a regular polygon that is not constructible by straightedge and compass.',
		8: '8 is the largest cube in the Fibonacci sequence.',
		9: '9 is the maximum number of cubes that are needed to sum to any positive integer.',
		10: '10 is the base of our number system.',
		11: '11 is the largest known multiplicative persistence.',
		12: '12 is the smallest abundant number.',
		13: '13 is the number of Archimedian solids.',
		14: '14 is the smallest even number n with no solutions to φ(m) = n.',
		15: '15 is the smallest composite number n with the property that there is only one group of order n.',
		16: '16 is the only number of the form xy = yx with x and y being different integers.',
		17: '17 is the number of wallpaper groups.',
		18: '18 is the only positive number that is twice the sum of its digits.',
		19: '19 is the maximum number of 4th powers needed to sum to any number.',
		20: '20 is the number of rooted trees with 6 vertices.',
		21: '21 is the smallest number of distinct squares needed to tile a square.',
		22: '22 is the number of partitions of 8.',
		23: '23 is the smallest number of integer-sided boxes that tile a box so that no two boxes share a common length.',
		24: '24 is the largest number divisible by all numbers less than its square root.',
		25: '25 is the smallest square that can be written as a sum of 2 squares.',
		26: '26 is the only positive number to be directly between a square and a cube.',
		27: '27 is the largest number that is the sum of the digits of its cube.',
		28: '28 is the 2nd perfect number.',
		29: '29 is the 7th Lucas number.',
		30: '30 is the largest number with the property that all smaller numbers relatively prime to it are prime.',
		31: '31 is a Mersenne prime.',
		32: '32 is the smallest non-trivial 5th power.',
		33: '33 is the largest number that is not a sum of distinct triangular numbers.',
		34: '34 is the smallest number with the property that it and its neighbors have the same number of divisors.',
		35: '35 is the number of hexominoes.',
		36: '36 is the smallest non-trivial number which is both square and triangular.',
		37: '37 is the maximum number of 5th powers needed to sum to any number.',
		38: '38 is the last Roman numeral when written lexicographically.',
		39: '39 is the smallest number which has 3 different partitions into 3 parts with the same product.',
		40: '40 is the only number whose letters are in alphabetical order.',
		41: '41 is a value of n so that x2 + x + n takes on prime values for x = 0, 1, 2, ... n-2.',
		42: '42 is the 5th Catalan number.',
		43: '43 is the number of sided 7-iamonds.',
		44: '44 is the number of derangements of 5 items.',
		45: '45 is a Kaprekar number.',
		46: '46 is the number of different arrangements (up to rotation and reflection) of 9 non-attacking queens on a 9×9 chessboard.',
		47: '47 is the largest number of cubes that cannot tile a cube.',
		48: '48 is the smallest number with 10 divisors.',
		49: '49 is the smallest number with the property that it and its neighbors are squareful.',
		50: '50 is the smallest number that can be written as the sum of of 2 squares in 2 ways.',
		51: '51 is the 6th Motzkin number.',
		52: '52 is the 5th Bell number.',
		53: '53 is the only two digit number that is reversed in hexadecimal.',
		54: '54 is the smallest number that can be written as the sum of 3 squares in 3 ways.',
		55: '55 is the largest triangular number in the Fibonacci sequence.',
		56: '56 is the number of reduced 5×5 Latin squares.',
		57: '57 = 111 in base 7.',
		58: '58 is the number of commutative semigroups of order 4.',
		59: '59 is the number of stellations of an icosahedron.',
		60: '60 is the smallest number divisible by 1 through 6.',
		61: '61 is the 3rd secant number.',
		62: '62 is the smallest number that can be written as the sum of of 3 distinct squares in 2 ways.',
		63: '63 is the number of partially ordered sets of 5 elements.',
		64: '64 is the smallest number with 7 divisors.',
		65: '65 is the smallest number that becomes square if its reverse is either added to or subtracted from it.',
		66: '66 is the number of 8-iamonds.',
		67: '67 is the smallest number which is palindromic in bases 5 and 6.',
		68: '68 is the 2-digit string that appears latest in the decimal expansion of π.',
		69: '69 is a value of n where n2 and n3 together contain each digit once.',
		70: '70 is the smallest weird number.',
		71: '71 divides the sum of the primes less than it.',
		72: '72 is the maximum number of spheres that can touch another sphere in a lattice packing in 6 dimensions.',
		73: '73 is the smallest multi-digit number which is one less than twice its reverse.',
		74: '74 is the number of different non-Hamiltonian polyhedra with a minimum number of vertices.',
		75: '75 is the number of orderings of 4 objects with ties allowed.',
		76: '76 is an automorphic number.',
		77: '77 is the largest number that cannot be written as a sum of distinct numbers whose reciprocals sum to 1.',
		78: '78 is the smallest number that can be written as the sum of of 4 distinct squares in 3 ways.',
		79: '79 is a permutable prime.',
		80: '80 is the smallest number n where n and n+1 are both products of 4 or more primes.',
		81: '81 is the square of the sum of its digits.',
		82: '82 is the number of 6-hexes.',
		83: '83 is the number of strongly connected digraphs with 4 vertices.',
		84: '84 is the largest order of a permutation of 14 elements.',
		85: '85 is the largest n for which 12+22+32+ ... +n2 = 1+2+3+ ... +m has a solution.',
		86: '86 = 222 in base 6.',
		87: '87 is the sum of the squares of the first 4 primes.',
		88: '88 is the only number known whose square has no isolated digits.',
		89: '89 = 8^1 + 9^2',
		90: '90 is the number of degrees in a right angle.',
		91: '91 is the smallest pseudoprime in base 3.',
		92: '92 is the number of different arrangements of 8 non-attacking queens on an 8×8 chessboard.',
		93: '93 = 333 in base 5.',
		94: '94 is a Smith number.',
		95: '95 is the number of planar partitions of 10.',
		96: '96 is the smallest number that can be written as the difference of 2 squares in 4 ways.',
		97: '97 is the smallest number with the property that its first 3 multiples contain the digit 9.',
		98: '98 is the smallest number with the property that its first 5 multiples contain the digit 9.',
		99: '99 is a Kaprekar number.',
		100: '100 is the smallest square which is also the sum of 4 consecutive cubes.',
		101: '101 is the number of partitions of 13.',
		102: '102 is the smallest number with three different digits.',
		103: '103 has the property that placing the last digit first gives 1 more than triple it.',
		104: '104 is the smallest known number of unit line segments that can exist in the plane, 4 touching at every vertex.',
		105: '105 is the largest number n known with the property that n - 2k is prime for k>1.',
		106: '106 is the number of trees with 10 vertices.',
		107: '107 is the exponent of a Mersenne prime.',
		108: '108 is 3 hyperfactorial.',
		109: '109 has a 5th root that starts 2.555555....',
		110: '110 is the smallest number that is the product of two different substrings.',
		111: '111 is the smallest possible magic constant of a 3×3 magic square of distinct primes.',
		112: '112 is the side of the smallest square that can be tiled with distinct integer-sided squares.',
		113: '113 is a permutable prime.',
		114: '114 = 222 in base 7.',
		115: '115 is the number of rooted trees with 8 vertices.',
		116: '116 is a value of n for which n! + 1 is prime.',
		117: '117 is the smallest possible value of the longest edge in a Heronian Tetrahedron.',
		118: '118 is the smallest number that has 4 different partitions into 3 parts with the same product.',
		119: '119 is the smallest number n where either n or n+1 is divisible by the numbers from 1 to 8.',
		120: '120 is the smallest number to appear 6 times in Pascal\'s triangle.',
		121: '121 is the only square of the form 1 + n + n2 + n3 + n4.',
		122: '122 is the smallest number n>1 so that n concatenated with n-1 0\'s concatenated with the reverse of n is prime.',
		123: '123 is the 10th Lucas number.',
		124: '124 is the smallest number with the property that its first 3 multiples contain the digit 2.',
		125: '125 is the only number known that contains all its proper divisors as proper substrings.',
		126: '126 = 9C4.',
		127: '127 is a Mersenne prime.',
		128: '128 is the largest number which is not the sum of distinct squares.',
		129: '129 is the smallest number that can be written as the sum of 3 squares in 4 ways.',
		130: '130 is the number of functions from 6 unlabeled points to themselves.',
		131: '131 is a permutable prime.',
		132: '132 is the smallest number which is the sum of all of the 2-digit numbers that can be formed with its digits.',
		133: '133 is the smallest number n for which the sum of the proper divisors of n divides φ(n).',
		134: '134 = 8C1 + 8C3 + 8C4.',
		135: '135 = 11 + 32 + 53.',
		136: '136 is the sum of the cubes of the digits of the sum of the cubes of its digits.',
		137: '137 is the smallest prime with 3 distinct digits that remains prime if one of its digits is removed.',
		138: '138 is a value of n for which n!!! - 1 is prime.',
		139: '139 is the number of unlabeled topologies with 5 elements.',
		140: '140 is a harmonic divisor number.',
		141: '141 is the 6th central trinomial coefficient.',
		142: '142 is the number of planar graphs with 6 vertices.',
		143: '143 is the smallest quasi-Carmichael number in base 8.',
		144: '144 is the largest square in the Fibonacci sequence.',
		145: '145 is a factorion.',
		146: '146 = 222 in base 8.',
		147: '147 is the number of sided 6-hexes.',
		148: '148 is the number of perfect graphs with 6 vertices.',
		149: '149 is the smallest number whose square begins with three 2\'s.',
		150: '150 = 100101102 = 21124 = 11005, each using 2 different digits an equal number of times.',
		151: '151 is a palindromic prime.',
		152: '152 has a square composed of the digits 0-4.',
		153: '153 is a narcissistic number.',
		154: '154 is the smallest number which is palindromic in bases 6, 8, and 9.',
		155: '155 is the sum of the primes between its smallest and largest prime factor.',
		156: '156 is the number of graphs with 6 vertices.',
		157: '157 is the smallest number with φ(2n+1) < φ(2n).',
		158: '158 is the number of planar partitions of 11.',
		159: '159 is the number of isomers of C11H24.',
		160: '160 is the number of 9-iamonds.',
		161: '161 is a Cullen number.',
		162: '162 is the smallest number that can be written as the sum of of 4 positive squares in 9 ways.',
		163: '163 is the largest Heegner Number.',
		164: '164 is the smallest number which is the concatenation of squares in two different ways.',
		165: '165 is the midpoint of the nth larger prime and nth smaller prime, for 1 ≤ n ≤ 6.',
		166: '166 is the number of monotone Boolean functions of 4 variables.',
		167: '167 is the smallest number whose 4th power begins with 4 identical digits',
		168: '168 is the size of the smallest non-cyclic simple group which is not an alternating group.',
		169: '169 is the 7th Pell number.',
		170: '170 is the smallest number n for which φ(n) and σ(n) are both square.',
		171: '171 has the same number of digits in Roman numerals as its cube.',
		172: '172 = 444 in base 6.',
		173: '173 has a square containing only 2 digits.',
		174: '174 is the smallest number that can be written as the sum of of 4 positive distinct squares in 6 ways.',
		175: '175 = 11 + 72 + 53.',
		176: '176 is an octagonal pentagonal number.',
		177: '177 is the number of graphs with 7 edges.',
		178: '178 has a cube with the same digits as another cube.',
		179: '179 has a square comprised of the digits 0-4.',
		180: '180 is the total number of degrees in a triangle.',
		181: '181 is a strobogrammatic prime.',
		182: '182 is the number of connected bipartite graphs with 8 vertices.',
		183: '183 is the smallest number n so that n concatenated with n+1 is square.',
		184: '184 is a Kaprekar constant in base 3.',
		185: '185 is the number of conjugacy classes in the automorphism group of the 8 dimensional hypercube.',
		186: '186 is the number of degree 11 irreducible polynomials over GF(2).',
		187: '187 is the smallest quasi-Carmichael number in base 7.',
		188: '188 is the number of semigroups of order 4.',
		189: '189 is a Kaprekar constant in base 2.',
		190: '190 is the largest number with the property that it and its ditinct prime factors are palindromic in Roman numerals.',
		191: '191 is a number n for which n, n+2, n+6, and n+8 are all prime.',
		192: '192 is the smallest number with 14 divisors.',
		193: '193 is the largest number that can be written as ab + ac + bc with 0 < a < b < c in a unique way.',
		194: '194 is the smallest number that can be written as the sum of 3 squares in 5 ways.',
		195: '195 is the smallest value of n such that 2nCn is divisible by n2.',
		196: '196 is the smallest number that is not known to reach a palindrome when repeatedly added to its reverse.',
		197: '197 is a Keith number.',
		198: '198 = 11 + 99 + 88.',
		199: '199 is the 11th Lucas number.',
		200: '200 is the smallest number which can not be made prime by changing one of its digits.',
		201: '201 is a Kaprekar constant in base 4.',
		202: '202 has a cube that contains only even digits.',
		203: '203 is the 6th Bell number.',
		204: '204 is the square root of a triangular number.',
		205: '205 = 5 × 41 = 5416.',
		206: '206 is the smallest number whose English name contains all five vowels exactly once.',
		207: '207 has a 4th power where the first half of the digits are a permutation of the last half of the digits.',
		208: '208 is the 10th Tetranacci number.',
		209: '209 is the smallest quasi-Carmichael number in base 9.',
		210: '210 is the product of the first 4 primes.',
		211: '211 has a cube containing only 3 different digits.',
		212: '212 has a square with 4/5 of the digits are the same.',
		213: '213 is the number of perfect squared rectangles of order 13.',
		214: '214 is a value of n for which n!! - 1 is prime.',
		215: '215 = 555 in base 6.',
		216: '216 is the smallest cube that can be written as the sum of 3 cubes.',
		217: '217 is a Kaprekar constant in base 2.',
		218: '218 is the number of digraphs with 4 vertices.',
		219: '219 is the number of space groups, not including handedness.',
		220: '220 is the smallest amicable number.',
		221: '221 is the number of Hamiltonian planar graphs with 7 vertices.',
		222: '222 is the number of lattices on 8 unlabeled nodes.',
		223: '223 is the smallest prime p which has more primitive roots below p/2 than above p/2.',
		224: '224 is the Entringer number E(6,3).',
		225: '225 is an octagonal square number.',
		226: '226 are the first 3 digits of π226.',
		227: '227 is the number of connected planar graphs with 8 edges.',
		228: '228 is the number of ways, up to rotation and reflection, of dissecting a regular 11-gon into 9 triangles.',
		229: '229 is the smallest prime that remains prime when added to its reverse.',
		230: '230 is the number of space groups, including handedness.',
		231: '231 is the number of partitions of 16.',
		232: '232 is the number of 7×7 symmetric permutation matrices.',
		233: '233 is the smallest number with the property that it and its neighbors can be written as a sum of 2 squares.',
		234: '234 is the number of ways to stack 12 pennies in a line so that each penny lies on the table or on two pennies.',
		235: '235 is the number of trees with 11 vertices.',
		236: '236 is the number of possible positions in Othello after 2 moves by both players.',
		237: '237 is the smallest number with the property that its first 3 multiples contain the digit 7.',
		238: '238 is the number of connected partial orders on 6 unlabeled elements.',
		239: '239 is the largest number that cannot be written as a sum of 8 or fewer cubes.',
		240: '240 is the smallest number with 20 divisors.',
		241: '241 is the only number n for which the nth prime is π(n π(n)).',
		242: '242 is the smallest n for which n, n+1, n+2, and n+3 have the same number of divisors.',
		243: '243 = 35.',
		244: '244 is the smallest number (besides 2) that can be written as the sum of 2 squares or the sum of two 5th powers.',
		245: '245 is a stella octangula number.',
		246: '246 = 9C2 + 9C4 + 9C6.',
		247: '247 is the smallest possible difference between two integers that together contain each digit exactly once.',
		248: '248 is the smallest number n>1 for which the arithmetic, geometric, and harmonic means of φ(n) and σ(n) are all integers.',
		249: '249 is the index of a prime Woodall number.',
		250: '250 is the smallest multi-digit number so that the sum of the squares of its prime factors equals the sum of the squares of its digits.',
		251: '251 is the smallest number that can be written as the sum of 3 cubes in 2 ways.',
		252: '252 is the 5th central binomial coefficient.',
		253: '253 is the smallest non-trivial triangular star number.',
		254: '254 is the smallest multi-digit composite number all of whose proper divisors contain the digit 2.',
		255: '255 = 11111111 in base 2.',
		256: '256 is the smallest non-trivial 8th power.',
		257: '257 is a Fermat prime.',
		258: '258 is a value of n so that n(n+9) is a palindrome.',
		259: '259 = 1111 in base 6.',
		260: '260 is the constant of an 8×8 magic square.',
		261: '261 is the number of essentially different ways to dissect a 16-gon into 7 quadrilaterals.',
		262: '262 is the 5th meandric number and the 9th open meandric number.',
		263: '263 is the largest known prime whose square is strobogrammatic.',
		264: '264 is the largest known number whose square is undulating.',
		265: '265 is the number of derangements of 6 items.',
		266: '266 is the Stirling number of the second kind S(8,6).',
		267: '267 is the number of planar partitions of 12.',
		268: '268 is the smallest number whose product of digits is 6 times the sum of its digits.',
		269: '269 is the number of 6-octs.',
		270: '270 is a harmonic divisor number.',
		271: '271 is the smallest prime p so that p-1 and p+1 are divisible by cubes.',
		272: '272 is the 4th tangent number.',
		273: '273 = 333 in base 9.',
		274: '274 is the Stirling number of the first kind s(6,2).',
		275: '275 is the number of partitions of 28 in which no part occurs only once.',
		276: '276 = 15 + 25 + 35.',
		277: '277 is a Perrin number.',
		278: '278 is the closest integer to 6π.',
		279: '279 is the maximum number of 8th powers needed to sum to any number.',
		280: '280 is the number of ways 18 people around a round table can shake hands in a non-crossing way, up to rotation.',
		281: '281 is the sum of the first 14 primes.',
		282: '282 is the number of planar partitions of 9.',
		283: '283 = 25 + 8 + 35.',
		284: '284 is an amicable number.',
		285: '285 is the number of binary rooted trees with 13 vertices.',
		286: '286 is the number of rooted trees with 9 vertices.',
		287: '287 is the sum of consecutive primes in 3 different ways.',
		288: '288 is the smallest non-palindrome non-square that when multiplied by its reverse is a square.',
		289: '289 is a Friedman number.',
		290: '290 has a base 3 representation that ends with its base 6 representation.',
		291: '291 is the largest number that is not the sum of distinct non-trivial powers.',
		292: '292 is the number of ways to make change for a dollar.',
		293: '293 is the number of ways to stack 20 boxes in a line so that each box lies on the table or on a box next to 2 boxes.',
		294: '294 is the number of planar 2-connected graphs with 7 vertices.',
		295: '295 is a structured deltoidal hexacontahedral number.',
		296: '296 is the number of partitions of 30 into distinct parts.',
		297: '297 is a Kaprekar number.',
		298: '298 is a value of n so that n(n+3) is a palindrome.',
		299: '299 is the maximum number of regions a cube can be cut into with 12 cuts.',
		300: '300 is the largest possible score in bowling.',
		301: '301 is a 6-hyperperfect number.',
		302: '302 is the number of ways to play the first 3 moves in Checkers.',
		303: '303 is the number of bipartite graphs with 8 vertices.',
		304: '304 is a primitive semiperfect number.',
		305: '305 is an hexagonal prism number.',
		306: '306 is the number of 5-digit triangular numbers.',
		307: '307 is a non-palindrome with a palindromic square.',
		308: '308 is a heptagonal pyramidal number.',
		309: '309 is the smallest number whose 5th power contains every digit at least once.',
		310: '310 = 1234 in base 6.',
		311: '311 is a permutable prime.',
		312: '312 = 2222 in base 5.',
		313: '313 is the number of intersections when all the diagonals of a regular dodecagon are drawn.',
		314: '314 is the smallest number that can be written as the sum of of 3 positive distinct squares in 6 ways.',
		315: '315 = (4+3) × (4+1) × (4+5).',
		316: '316 has a digit product which is the digit sum of (31)6.',
		317: '317 is the number of binary 4×4 matrices up to permutations of rows and columns.',
		318: '318 is the number of unlabeled partially ordered sets of 6 elements.',
		319: '319 is the smallest number with the property that the partition with the largest product does not have a maximum number of parts.',
		320: '320 is the maximum determinant of a binary 10×10 matrix.',
		321: '321 is a Delannoy number.',
		322: '322 is the 12th Lucas number.',
		323: '323 is the smallest composite number n that divides the (n+1)st Fibonacci number.',
		324: '324 is the largest possible product of positive integers with sum 16.',
		325: '325 is a 3-hyperperfect number.',
		326: '326 is the number of permutations of some subset of 5 elements.',
		327: '327 is the largest number n so that n, 2n, and 3n together contain every digit from 1-9 exactly once.',
		328: '328 concatenated with its successor is square.',
		329: '329 is the number of forests with 10 vertices.',
		330: '330 = 11C4.',
		331: '331 is both a centered pentagonal number and a centered hexagonal number.',
		332: '332 is the number of 2-connected graphs with 7 vertices',
		333: '333 is the number of 7-hexes.',
		334: '334 is the number of trees on 13 vertices with diameter 7.',
		335: '335 is the number of degree 12 irreducible polynomials over GF(2).',
		336: '336 = 8P3.',
		337: '337 is the number of different resistances that can be created in a circuit of 8 equal resistors.',
		338: '338 is the smallest number for which both the number of divisors and the sum of its prime factors is a perfect number.',
		339: '339 is the number of ways to divide 5 black and 5 white beads into piles.',
		340: '340 is a value of n for which n! + 1 is prime.',
		341: '341 is the smallest pseudoprime in base 2.',
		342: '342 is the number of inequivalent binary linear codes of length 8.',
		343: '343 is a strong Friedman number.',
		344: '344 is the smallest number that can be written as the sum of a cube and a 7th power in more than one way.',
		345: '345 is half again as large as the sum of its proper divisors.',
		346: '346 is a Franel number.',
		347: '347 is a Friedman number.',
		348: '348 is the smallest number whose 5th power contains exactly the same digits as another 5th power.',
		349: '349 is a Tetranacci-like number starting from 1, 1, 1, and 1.',
		350: '350 is the Stirling number of the second kind S(7,4).',
		351: '351 is the smallest number so that it and the surrounding numbers are all products of 4 or more primes.',
		352: '352 is the number of different arrangements of 9 non-attacking queens on an 9×9 chessboard.',
		353: '353 is the smallest number whose 4th power can be written as the sum of four 4th powers.',
		354: '354 is the sum of the first four 4th powers.',
		355: '355 is the number of labeled topologies with 4 elements.',
		356: '356 is the smallest happy number of height 6.',
		357: '357 has a base 3 representation that ends with its base 7 representation.',
		358: '358 has a base 3 representation that ends with its base 7 representation.',
		359: '359 has a base 3 representation that ends with its base 7 representation.',
		360: '360 is the number of degrees in a circle.',
		361: '361 is the number of intersections on a Go board.',
		362: '362 and its double and triple all use the same number of digits in Roman numerals.',
		363: '363 is a perfect totient number.',
		364: '364 = 14C3.',
		365: '365 is the smallest number that can be written as a sum of consecutive squares in more than 1 way.',
		366: '366 is the number of days in a leap year.',
		367: '367 is the largest number whose square has strictly increasing digits.',
		368: '368 is the number of ways to tile a 4×15 rectangle with the pentominoes.',
		369: '369 is the number of octominoes.',
		370: '370 is a narcissistic number.',
		371: '371 is a narcissistic number.',
		372: '372 is a hexagonal pyramidal number.',
		373: '373 is a permutable prime.',
		374: '374 is the smallest number that can be written as the sum of 3 squares in 8 ways.',
		375: '375 is a truncated tetrahedral number.',
		376: '376 is an automorphic number.',
		377: '377 is the 14th Fibonacci number.',
		378: '378 is the maximum number of regions a cube can be cut into with 13 cuts.',
		379: '379 is a value of n for which one more than the product of the first n primes is prime.',
		380: '380 is the number of necklaces possible with 13 beads, each being one of 2 colors.',
		381: '381 is a Kaprekar constant in base 2.',
		382: '382 is the smallest number n with σ(n) = σ(n+3).',
		383: '383 is the number of Hamiltonian graphs with 7 vertices.',
		384: '384 = 8!! = 12!!!!.',
		385: '385 is the number of partitions of 18.',
		386: '386 is the number of regions the complex plane is cut into by drawing lines between all pairs of 11th roots of unity.',
		387: '387 is the smallest number with sort-then-add persistence of 10.',
		388: '388 is the maximum value of n so that there exist 6 denominations of stamps so that every postage from 1 to n can be paid for with at most 6 stamps.',
		389: '389 is the smallest prime so that it and the next 3 primes are all equal to 1 (mod 4).',
		390: '390 is the number of partitions of 32 into distinct parts.',
		392: '392 is a Kaprekar constant in base 5.',
		393: '393 is the 7th central trinomial coefficient.',
		394: '394 is a Schröder number.',
		395: '395 does not occur in its factorial in base 2.',
		396: '396 is the number of 3×3 sliding puzzle positions that require exactly 11 moves to solve starting with the hole in a corner.',
		397: '397 is a Cuban prime.',
		398: '398 is the number of integers with complexity 22.',
		399: '399 is a Lucas-Carmichael number.',
		400: '400 = 1111 in base 7.',
		401: '401 is the number of connected planar Eulerian graphs with 9 vertices.',
		402: '402 is the number of graphs with 8 vertices and 9 edges.',
		403: '403 is the product of two primes which are reverses of each other.',
		404: '404 is the number of sided 10-hexes with holes.',
		405: '405 is a pentagonal pyramidal number.',
		406: '406 is the number of ways to tile a 3×17 rectangle with 3×1 rectangles.',
		407: '407 is a narcissistic number.',
		408: '408 is the 8th Pell number.',
		409: '409 is the number of graphs with 8 vertices with clique number 2.',
		410: '410 is the smallest number that can be written as the sum of 2 distinct prime powers in 2 ways.',
		411: '411 is a member of the Fibonacci-type sequence starting with 1 and 4.',
		412: '412 is the number of subsets of {1,2,3,...,11} that have a sum divisible by 5.',
		413: '413 is a structured hexagonal diamond number.',
		414: '414 is a value of n for which n4, n5, n6, and n7 have the same digit sum.',
		415: '415 is the 10th Iccanobif number, where each term is the reverse of the sum of the previous two numbers.',
		416: '416 is the number of subsets of the 15th roots of unity that add to a real number.',
		417: '417 is the smallest number so that it and the next 3 numbers have different numbers of distinct prime factors.',
		418: '418 has the property that the sum of its prime factors is equal to the product of its digits.',
		419: '419 is the number of ways to divide a 6×6 grid of points into two sets using a straight line.',
		420: '420 is the smallest number divisible by 1 through 7.',
		421: '421 is the number of commutative monoids of order 6.',
		422: '422 is the smallest number whose 8th power has 21 digits.',
		423: '423 is a number that does not have any digits in common with its cube.',
		425: '425 is the number of subsets of {1,2,3,...,11} that have an integer average.',
		426: '426 is a stella octangula number.',
		427: '427 is a value of n for which n! + 1 is prime.',
		428: '428 has the property that its square is the concatenation of two consecutive numbers.',
		429: '429 is the 7th Catalan number.',
		430: '430 is the number of necklaces possible with 6 beads, each being one of 4 colors.',
		431: '431 is the index of a prime Fibonacci number.',
		432: '432 = 4 × 33 × 22.',
		433: '433 is the index of a prime Fibonacci number.',
		434: '434 is the smallest composite value of n for which σ(n) + 2 = σ(n+2).',
		435: '435 is the number of ordered partitions of 16 into distinct parts.',
		436: '436 is the smallest number whose cube contains four 8\'s.',
		437: '437 has a cube with the last 3 digits the same as the 3 digits before that.',
		438: '438 = 666 in base 8.',
		439: '439 is the smallest prime where inserting the same digit between every pair of digits never yields another prime.',
		440: '440 is the number of permutations of 12 items that fix 9 elements.',
		441: '441 is the smallest square which is the sum of 6 consecutive cubes.',
		442: '442 is the number of planar partitions of 13.',
		443: '443 is a value of n for which σ(n) is a repdigit.',
		444: '444 is the largest known n for which there is a unique integer solution to a1+ ... +an = (a1)...(an).',
		445: '445 has a base 10 representation which is the reverse of its base 9 representation.',
		446: '446 is the smallest number that can be written as the sum of 3 distinct squares in 8 ways.',
		447: '447 is the smallest number of convex quadrilaterals formed by 15 points in general position.',
		448: '448 is the number of 10-iamonds.',
		449: '449 has a base 3 representation that begins with its base 7 representation.',
		450: '450 is the number of 13-iamonds with holes.',
		451: '451 is the smallest number whose reciprocal has period 10.',
		452: '452 is the closest integer to 7π.',
		453: '453 is the only number n so that n, 2n, and 6n together contain every digit exactly once.',
		454: '454 is the largest number known that cannot be written as a sum of 7 or fewer cubes.',
		455: '455 = 15C3.',
		456: '456 is the number of tournaments with 7 vertices.',
		457: '457 is the index of a prime Euclid number.',
		458: '458 is a number that does not have any digits in common with its cube.',
		459: '459 is the smallest number n for which reverse(n) - n contains the same digits as n.',
		461: '461 is the number of ways to stack 18 pennies in contiguous rows so that each penny lies on the table or on two pennies.',
		462: '462 = 11C5.',
		463: '463 is the smallest prime so that it and the next 6 primes are all equal to 3 (mod 4).',
		464: '464 is the maximum number of regions space can be divided into by 12 spheres.',
		465: '465 is a Kaprekar constant in base 2.',
		466: '466 = 1234 in base 7.',
		467: '467 has strictly increasing digits in bases 7, 9, and 10.',
		468: '468 = 3333 in base 5.',
		469: '469 is a value of n for which n! - 1 is prime.',
		470: '470 has a base 3 representation that ends with its base 6 representation.',
		471: '471 is the smallest number with the property that its first 4 multiples contain the digit 4.',
		472: '472 is the number of ways to tile a 5×5 square with integer-sided squares.',
		473: '473 is the largest known number whose square and 4th power use different digits.',
		474: '474 is a member of the Fibonacci-type sequence starting with 1 and 8.',
		475: '475 has a square that is composed of overlapping squares of smaller numbers.',
		476: '476 is the number of different products of subsets of the set {1, 2, 3, ... 11}.',
		477: '477 is the smallest number whose cube contains four 3\'s.',
		478: '478 is the 7th Pell-Lucas number.',
		479: '479 is the number of sets of distinct positive integers with mean 6.',
		480: '480 is the smallest number which can be written as the difference of 2 squares in 8 ways.',
		481: '481 is the number of conjugacy classes in the automorphism group of the 10 dimensional hypercube.',
		482: '482 is a number whose square and cube use different digits.',
		483: '483 is the last 3-digit string in the decimal expansion of π.',
		484: '484 is a palindrome in base 3 and in base 10.',
		485: '485 is the number of categories with 6 morphisms and 2 objects.',
		486: '486 is a Perrin number.',
		487: '487 is the number of Hadamard matrices of order 28.',
		489: '489 is an octahedral number.',
		490: '490 is the number of partitions of 19.',
		491: '491 is the smallest number n so that the largest prime factors of the numbers n through n+4 decrease.',
		492: '492 is a Hexanacci number.',
		493: '493 is a Lucas 7-step number.',
		494: '494 is the number of unlabeled distributive lattices with 14 elements.',
		495: '495 is the Kaprekar constant for 3-digit numbers.',
		496: '496 is the 3rd perfect number.',
		497: '497 is the number of graphs with 8 edges.',
		498: '498 is the number of necklaces possible with 8 beads, each being one of 3 colors.',
		499: '499 is the number of ways to place 26 points on a 13×13 grid so that no 3 points are on a line.',
		500: '500 is the number of planar partitions of 10.',
		501: '501 is the number of partitions of 5 items into ordered lists.',
		502: '502 uses the same digits as φ(502).',
		503: '503 is the smallest prime which is the sum of the cubes of the first few primes.',
		504: '504 = 9P3.',
		505: '505 = 10C5 + 10C0 + 10C5.',
		506: '506 is the sum of the first 11 squares.',
		507: '507 is the number of rooted ternary trees with 10 vertices.',
		509: '509 is the index of a prime Fibonacci number.',
		510: '510 is the number of binary rooted trees with 14 vertices.',
		511: '511 = 111111111 in base 2.',
		512: '512 is the cube of the sum of its digits.',
		513: '513 is the number of conjugacy classes of the alternating group A22.',
		514: '514 is the smallest number whose cube begins with 13579.',
		515: '515 is the number of graphs on 6 vertices with no isolated vertices.',
		516: '516 is the number of partitions of 32 in which no part occurs only once.',
		517: '517 does not occur in its factorial in base 2.',
		518: '518 = 51 + 12 + 83.',
		519: '519 is the number of trees on 15 vertices with diameter 5.',
		520: '520 is the number of ways to place 2 non-attacking kings on a 6×6 chessboard.',
		521: '521 is the 13th Lucas number.',
		522: '522 is the number of ways to place a non-attacking white and black pawn on a 6×6 chessboard.',
		523: '523 is the smallest prime that is followed by 17 composite numbers.',
		524: '524 is the number of 6-kings.',
		525: '525 is a hexagonal pyramidal number.',
		526: '526 is the number of ways to cut a 8×8 chessboard into 2 pieces with equal areas with a cut that only travels up and right.',
		527: '527 is the smallest number n for which there do not exist 4 smaller numbers so that a1! a2! a3! a4! n! is square.',
		528: '528 concatenated with its successor is square.',
		529: '529 is the smallest number n so that the continued fraction for n/k contains no 2\'s for any 1 ≤ k ≤ n.',
		530: '530 is the sum of the first 3 perfect numbers.',
		531: '531 is the smallest number with the property that its first 4 multiples contain the digit 1.',
		532: '532 is a hendecagonal pyramidal number.',
		533: '533 is the number of degree sequences for graphs with 5 vertices.',
		535: '535 is a palindrome whose φ(n) is also palindromic.',
		536: '536 is the number of solutions of the stomachion puzzle.',
		537: '537 divides the sum of the cubes of the first 537 primes.',
		538: '538 is the 10th open meandric number.',
		539: '539 is the number of multigraphs with 5 vertices and 9 edges.',
		540: '540 is divisible by its reverse.',
		541: '541 is the number of orderings of 5 objects with ties allowed.',
		542: '542 is a member of the Fibonacci-type sequence starting with 3 and 8.',
		543: '543 is a number whose square and cube use different digits.',
		544: '544 is the generalized Catalan number C(14,3).',
		545: '545 has a base 3 representation that begins with its base 4 representation.',
		546: '546 undulates in bases 3, 4, and 5.',
		547: '547 is the smallest number that can not be written using 11 copies of 11 and the operations +, –, ×, and ÷.',
		548: '548 is the maximum number of 9th powers needed to sum to any number.',
		550: '550 is a pentagonal pyramidal number.',
		551: '551 is the number of trees with 12 vertices.',
		552: '552 is the number of prime knots with 11 crossings.',
		553: '553 is a Huay rhombic dodecahedral number.',
		554: '554 is the number of self-dual planar graphs with 20 edges.',
		555: '555 is a repdigit.',
		556: '556 are the first 3 digits of 4556.',
		558: '558 divides the sum of the largest prime factors of the first 558 positive integers.',
		559: '559 is a centered cube number.',
		560: '560 = 16C3.',
		561: '561 is the smallest Carmichael number.',
		562: '562 is the maximum number of regions a circle can be cut into by joining 11 points on the circumference with straight lines.',
		563: '563 is the largest known Wilson prime.',
		564: '564 is the number of 13-ominoes with a horizontal or vertical line of symmetry.',
		565: '565 is a structured truncated octahedral number.',
		566: '566 is the number of ways to place 24 points on a 12×12 grid so that no 3 points are on a line.',
		567: '567 has the property that it and its square together use the digits 1-9 once.',
		568: '568 is the smallest number whose 7th power can be written as the sum of seven 7th powers.',
		569: '569 is the smallest number n for which the concatenation of n, (n+1), ... (n+30) is prime.',
		570: '570 is the product of all the prime palindromic Roman numerals.',
		571: '571 is the index of a prime Fibonacci number.',
		572: '572 is the smallest number which has equal numbers of every digit in bases 2 and 3.',
		573: '573 has the property that its square is the concatenation of two consecutive numbers.',
		574: '574 is the maximum number of pieces a torus can be cut into with 14 cuts.',
		575: '575 is a palindrome that is one less than a square.',
		576: '576 is the number of 4×4 Latin squares.',
		577: '577 is a Proth prime.',
		578: '578 is the number of graphs with 7 vertices with clique number 3.',
		579: '579 is the number of graphs with 7 vertices that have chromatic number 3.',
		580: '580 is the 6th central quadrinomial coefficient.',
		581: '581 has a base 3 representation that begins with its base 4 representation.',
		582: '582 is the number of antisymmetric relations on a 5 element set.',
		583: '583 is the smallest number whose reciprocal has period 26.',
		584: '584 is the number of ways to color the vertices of a triangle with 12 colors, up to rotation.',
		585: '585 is a palindrome in base 2, base 8, and in base 10.',
		586: '586 is the smallest number that appears in its factorial 6 times.',
		587: '587 is the smallest number whose digit sum is larger than that of its cube.',
		588: '588 is the number of possible rook moves on a 7×7 chessboard.',
		589: '589 is a centered tetrahedral number.',
		590: '590 is a value of n for which φ(n) + φ(n+1) divides σ(n) + σ(n+1).',
		591: '591 is the number of ways to stack 23 boxes in a line so that each box lies on the table or on a box next to 2 boxes.',
		592: '592 evenly divides the sum of its rotations.',
		593: '593 is a Leyland number.',
		594: '594 = 15 + 29 + 34.',
		595: '595 is the number of ways to tile a 3×18 rectangle with 3×1 rectangles.',
		596: '596 is the number of Hamiltonian cycles of a 4×9 rectangle graph.',
		597: '597 is a value of n for which n!!! + 1 is prime.',
		598: '598 = 51 + 92 + 83.',
		599: '599 is the smallest number whose digits add to 23.',
		600: '600 and its reverse are both the averages of twin primes.',
		601: '601 is the location of the first occurrence of 3 consecutive zeroes in the decimal digits of π.',
		602: '602 are the first 3 digits of 5602.',
		603: '603 is the smallest number n so that n, n+1, and n+2 are all the product of a prime and the square of a prime.',
		604: '604 and the two numbers before it and after it are all products of exactly 3 primes.',
		605: '605 has a sum of digits equal to its largest prime factor.',
		606: '606 is the first non-trivial number that is both 11-gonal and centered 11-gonal.',
		607: '607 is the exponent of a Mersenne prime.',
		608: '608 is a number that does not have any digits in common with its cube.',
		609: '609 is a strobogrammatic number.',
		610: '610 is the smallest Fibonacci number that begins with 6.',
		612: '612 is a number whose square and cube use different digits.',
		613: '613 is the index of a prime Lucas number.',
		614: '614 is the smallest number that can be written as the sum of 3 squares in 9 ways.',
		615: '615 is the trinomial coefficient T(10,6).',
		616: '616 is a Padovan number.',
		617: '617 = 1!2 + 2!2 + 3!2 + 4!2.',
		618: '618 is the number of ternary square-free words of length 15.',
		619: '619 is a strobogrammatic prime.',
		620: '620 is the number of sided 7-hexes.',
		621: '621 is the number of ways to 9-color the faces of a tetrahedron.',
		623: '623 is the number of inequivalent asymmetric Ferrers graphs with 23 points.',
		624: '624 is the smallest number with the property that its first 5 multiples contain the digit 2.',
		625: '625 is an automorphic number.',
		626: '626 is a palindrome in base 5 and in base 10.',
		627: '627 is the number of partitions of 20.',
		628: '628 is the sum of the squares of 4 consecutive primes.',
		629: '629 evenly divides the sum of its rotations.',
		630: '630 is a triangular number, 3 times a triangular number, and 6 times a triangular number.',
		631: '631 has a base 2 representation that begins with its base 5 representation.',
		632: '632 is the number of triangles formed by connecting the diagonals of a regular octagon.',
		633: '633 is the smallest number n whose 5th root has a decimal part that begins with the digits of n.',
		634: '634 is a number n whose 5th root has a decimal part that begins with the digits of n.',
		635: '635 is a number n whose 5th root has a decimal part that begins with the digits of n.',
		636: '636 is a number n whose 5th root has a decimal part that begins with the digits of n.',
		637: '637 = 777 in base 9.',
		638: '638 is the number of fixed 5-kings.',
		639: '639 is a number n whose 5th root has a decimal part that begins with the digits of n.',
		640: '640 = 16!!!!!!.',
		641: '641 is the smallest prime factor of 225+1.',
		642: '642 is the smallest number with the property that its first 6 multiples contain the digit 2.',
		643: '643 is the largest prime factor of 123456.',
		644: '644 is a Perrin number.',
		645: '645 is the largest n for which 1+2+3+ ... +n = 12+22+32+ ... +k2 for some k.',
		646: '646 is the number of connected planar graphs with 7 vertices.',
		648: '648 is the smallest number whose decimal part of its 6th root begins with the digits 1-9 in some order.',
		649: '649 is the smallest number n so that n2 is 1 more than 13 times a square.',
		650: '650 is the sum of the first 12 squares.',
		651: '651 has a 4th power that is the sum of four 4th powers.',
		652: '652 is the only known non-perfect number whose number of divisors and sum of smaller divisors are perfect.',
		653: '653 is the only known prime for which 5 is neither a primitive root or a quadratic residue of 4n2+1.',
		654: '654 has a square that is the sum of a cube and 5th power.',
		656: '656 is a palindrome in base 3 and in base 10.',
		657: '657 is the number of ways to tile a 4×22 rectangle with 4×1 rectangles.',
		658: '658 is the number of triangles of any size contained in the triangle of side 13 on a triangular grid.',
		659: '659 is an Eisenstein-Mersenne prime.',
		660: '660 is the order of a non-cyclic simple group.',
		661: '661 is the largest prime factor of 8! + 1.',
		662: '662 is the index of the smallest triangular number that contains the digits 1, 2, 3, 4, and 5.',
		663: '663 is the generalized Catalan number C(15,3).',
		664: '664 is a value of n so that n(n+7) is a palindrome.',
		665: '665 is a member of the Fibonacci-type sequence starting with 1 and 4.',
		666: '666 is the largest rep-digit triangular number.',
		667: '667 is the number of asymmetric trees with 16 vertices.',
		668: '668 is the number of legal pawn moves in Chess.',
		669: '669 is the number of unsymmetrical ways to dissect a regular 12-gon into 10 triangles.',
		670: '670 is an octahedral number.',
		671: '671 is a rhombic dodecahedral number.',
		672: '672 is a multi-perfect number.',
		673: '673 is a Tetranacci-like number starting from 1, 1, 1, and 1.',
		675: '675 is the smallest order for which there are 17 groups.',
		676: '676 is the smallest palindromic square number whose square root is not palindromic.',
		677: '677 is the closest integer to 11e.',
		678: '678 is a member of the Fibonacci-type sequence starting with 1 and 7.',
		679: '679 is the smallest number with multiplicative persistence 5.',
		680: '680 is the smallest tetrahedral number that is also the sum of 2 tetrahedral numbers.',
		681: '681 divides the sum of the first 681 composite numbers.',
		682: '682 = 11C6 + 11C8 + 11C2.',
		683: '683 is a Wagstaff prime.',
		684: '684 is the sum of 3 consecutive cubes.',
		686: '686 is the number of partitions of 35 in which no part occurs only once.',
		687: '687 is the closest integer to 8π.',
		688: '688 is a Friedman number.',
		689: '689 is the smallest number that can be written as the sum of 3 distinct squares in 9 ways.',
		690: '690 is the smallest number that can not be written as the sum of a triangular number, a cube, and a Fibonacci number.',
		691: '691 is the smallest prime p for which x5 = x4 + x3 + x2 + x + 1 (mod p) has 5 solutions.',
		692: '692 is a number that does not have any digits in common with its cube.',
		693: '693 are the first 3 decimal digits of ln(2).',
		694: '694 is the number of different arrangements (up to rotation and reflection) of 7 non-attacking rooks on a 7×7 chessboard.',
		695: '695 is the maximum number of pieces a torus can be cut into with 15 cuts.',
		696: '696 is a palindrome n so that n(n+8) is also palindromic.',
		697: '697 is a 12-hyperperfect number.',
		698: '698 = 32 + 43 + 54.',
		699: '699 is a value of n for which |cos(n)| is smaller than any previous integer.',
		700: '700 is the number of symmetric 8-cubes.',
		701: '701 = 10 + 21 + 32 + 43 + 54.',
		703: '703 is a Kaprekar number.',
		704: '704 is the number of sided octominoes.',
		705: '705 is the smallest Lucas pseudoprime.',
		707: '707 is the smallest number whose reciprocal has period 12.',
		708: '708 is the maximum value of n so that there exist 4 denominations of stamps so that every postage from 1 to n can be paid for with at most 12 stamps.',
		709: '709 is the number of connected planar graphs with 9 edges.',
		710: '710 is the number of connected graphs with 9 edges.',
		711: '711 is the name of a chain of convenience stores.',
		712: '712 is the largest number known that does not have any digits in common with its 8th power.',
		713: '713 is the number of commutative monoids of order 7 with 4 idempotents.',
		714: '714 is the smallest number which has equal numbers of every digit in bases 2 and 5.',
		715: '715 = 13C4.',
		716: '716 is the smallest number whose cube contains four 6\'s.',
		717: '717 is a palindrome in base 2 and in base 10.',
		718: '718 is the number of unlabeled topologies with 6 elements.',
		719: '719 is the number of rooted trees with 10 vertices.',
		720: '720 = 6!',
		721: '721 is the smallest number which can be written as the difference of 2 cubes in 2 ways.',
		722: '722 is the sum of the 4th powers of the first 3 primes.',
		723: '723 = (1!)! + (2!)! + (3!)!.',
		724: '724 is the number of different arrangements of 10 non-attacking queens on an 10×10 chessboard.',
		726: '726 is the number of 4-step self-avoiding walks on the cubic lattice.',
		727: '727 has the property that its square is the concatenation of two consecutive numbers.',
		728: '728 is the smallest number n where n and n+1 are both products of 5 or more primes.',
		729: '729 = 36.',
		730: '730 is the number of connected bipartite graphs with 9 vertices.',
		731: '731 is the number of planar partitions of 14.',
		732: '732 = 17 + 26 + 35 + 44 + 53 + 62 + 71.',
		733: '733 is the sum of the digits of 444.',
		734: '734 is the smallest number that can be written as the sum of 3 distinct non-zero squares in 10 ways.',
		735: '735 is the smallest number that is the concatenation of its distinct prime factors.',
		736: '736 is a strong Friedman number.',
		737: '737 is a Boeing plane.',
		738: '738 = 6 + 66 + 666.',
		739: '739 has a base 2 representation that begins with its base 9 representation.',
		740: '740 is the number of self-avoiding walks of length 8.',
		741: '741 is the number of multigraphs with 6 vertices and 8 edges.',
		742: '742 is the smallest number that is one more than triple its reverse.',
		743: '743 is the number of independent sets of the graph of the 4-dimensional hypercube.',
		744: '744 is the number of perfect squared rectangles of order 14.',
		745: '745 is the smallest number whose square begins with three 5\'s.',
		746: '746 = 17 + 24 + 36.',
		747: '747 is a Boeing plane.',
		748: '748 is the number of 3×3 sliding puzzle positions that require exactly 12 moves to solve starting with the hole in a corner.',
		749: '749 is the number of ways to divide a 7×7 grid of points into two sets using a straight line.',
		750: '750 is the Stirling number of the second kind S(10,8).',
		751: '751 is the index of a prime Woodall number.',
		752: '752 is the number of conjugacy classes in the automorphism group of the 11 dimensional hypercube.',
		753: '753 is the smallest number whose cube contains 4 consecutive 7\'s.',
		755: '755 is the number of trees on 14 vertices with diameter 6.',
		756: '756 is the maximum number of regions space can be divided into by 14 spheres.',
		757: '757 is the smallest number whose reciprocal has a period of 27.',
		759: '759 is the number of octads in the large Witt design.',
		760: '760 is the number of partitions of 37 into distinct parts.',
		762: '762 is the starting location of 999999 in the decimal expansion of π.',
		763: '763 is the smallest number whose 4th power contains every digit at least once.',
		764: '764 is the number of 8×8 symmetric permutation matrices.',
		765: '765 is a Kaprekar constant in base 2.',
		766: '766 is the number of series-reduced planted trees with 9 leaves.',
		767: '767 is the largest n so that n2 = mC0 + mC1 + mC2 + mC3 has a solution.',
		768: '768 is the number of subsets of {1,2,3,...,12} that have an integer average.',
		769: '769 is the total number of digits of all binary numbers of length 1-7.',
		770: '770 is the number of digits of the 15th perfect number.',
		771: '771 is the number of intersections when all the diagonals of a regular 14-gon are drawn.',
		773: '773 is the smallest odd number n so that n+2k is composite for all k<n.',
		775: '775 is the smallest number whose 9th power has 26 digits.',
		777: '777 is a repdigit in base 6 and in base 10.',
		778: '778 is the number of ways a 5×1 rectangle can be surrounded by 5×1 rectangles.',
		780: '780 = (5+7) × (5+8) × (5+0).',
		781: '781 = 11111 in base 5.',
		782: '782 is a number whose sum of divisors is a 4th power.',
		783: '783 is the number of 11-ominoes that tile the plane by translation.',
		784: '784 is the sum of the first 7 cubes.',
		785: '785 are the last 3 digits of the sum of the first 785 squares.',
		786: '786 is the largest known n for which 2nCn is not divisible by the square of an odd prime.',
		787: '787 is a palindrome in base 3 and in base 10.',
		788: '788 is the smallest of 6 consecutive numbers divisible by 6 consecutive primes.',
		789: '789 are the first 3 digits of 9789.',
		791: '791 is the smallest number n where either it or its neighbors are divisible by the numbers from 1 to 12.',
		792: '792 is the number of partitions of 21.',
		793: '793 is one less than twice its reverse.',
		794: '794 = 16 + 26 + 36.',
		795: '795 is a number whose sum of divisors is a 4th power.',
		797: '797 is the number of functional graphs on 9 vertices.',
		798: '798 is the number of ternary square-free words of length 16.',
		799: '799 is the smallest number whose sum of digits is composite and whose sum of digits cubed is prime.',
		800: '800 = 2222 in base 7.',
		801: '801 = (7! + 8! + 9! + 10!) / (7 × 8 × 9 × 10).',
		802: '802 is the number of isomers of C13H28.',
		803: '803 is a value of n for which σ(n) is a repdigit.',
		804: '804 is a value of n for which 2φ(n) = φ(n+1).',
		805: '805 is the number of possible positions in Checkers after 4 moves.',
		806: '806 is not the sum of a square, a cube, a 4th power, and a 5th power.',
		808: '808 is a strobogrammatic number.',
		809: '809 is a member of the Fibonacci-type sequence starting with 1 and 5.',
		810: '810 is a value of n for which n-1 and n+1 are twin primes, and so are 2n-1 and 2n+1.',
		811: '811 is the smallest prime factor of 24! + 1.',
		812: '812 is the number of triangles of any size contained in the triangle of side 14 on a triangular grid.',
		813: '813 are the first 3 digits of 813e.',
		814: '814 is a value of n so that n(n+5) is a palindrome.',
		815: '815 is a Lucas 3-step number.',
		816: '816 = 18C3.',
		818: '818 is the number of ways to dissect a 12-gon using non-crossing diagonals into polygons with an even number of sides.',
		819: '819 is the smallest number so that it and its successor are both the product of 2 primes and the square of a prime.',
		820: '820 = 1111 in base 9.',
		821: '821 is a number n for which n, n+2, n+6, and n+8 are all prime.',
		822: '822 is the number of planar graphs with 7 vertices.',
		823: '823 is a number that does not have any digits in common with its cube.',
		825: '825 is the number of ways to legally add 2 sets of parentheses to a product of 9 variables.',
		827: '827 is the number of asymmetric trees with 11 vertices.',
		829: '829 is a value of n for which π(n) is the product of the digits of n.',
		831: '831 is the number of monic polynomials of degree 9 with integer coefficients whose complex roots are all in the unit disk.',
		832: '832 is the maximum number of pieces a torus can be cut into with 16 cuts.',
		833: '833 is a centered octahedral number.',
		834: '834 is the maximum number of regions a cube can be cut into with 17 cuts.',
		835: '835 is the 9th Motzkin number.',
		836: '836 is a non-palindrome with a palindromic square.',
		839: '839 has a base 5 representation that begins with its base 9 representation.',
		840: '840 is the smallest number divisble by 1 through 8.',
		841: '841 is a square that is also the sum of 2 consecutive squares.',
		842: '842 is the ratio of Fibonacci numbers.',
		843: '843 is the 14th Lucas number.',
		844: '844 is the smallest number so that it and the next four numbers are squareful numbers.',
		846: '846 has the property that its square is the concatenation of two consecutive numbers.',
		847: '847 is the sum of the digits of the 14th Mersenne prime.',
		848: '848 is the number of inequivalent binary linear codes of length 9.',
		849: '849 is a value of n for which σ(n-1) = σ(n+1).',
		850: '850 is the number of trees on 14 vertices with diameter 7.',
		851: '851 is the number of ordered partitions of 18 into distinct parts.',
		852: '852 is the number of 6-colorable connected graphs with 7 vertices.',
		853: '853 is the number of connected graphs with 7 vertices.',
		854: '854 has the property that it and its square together use the digits 1-9 once.',
		855: '855 is the smallest number which is the sum of 5 consecutive squares or 2 consecutive cubes.',
		856: '856 is a member of the Fibonacci-type sequence starting with 1 and 9.',
		857: '857 is a value of n for which φ(n) = φ(n-1) + φ(n-2).',
		858: '858 is the smallest palindrome with 4 different prime factors.',
		859: '859 is the number of planar partitions of 11.',
		861: '861 = 7 + 77 + 777.',
		862: '862 is a number whose sum of divisors is a 4th power.',
		863: '863 is a value of n so that n(n+6) is a palindrome.',
		864: '864 is the number of partitions of 38 into distinct parts.',
		866: '866 is the number of sided 10-iamonds.',
		867: '867 is the number of graphs with 8 vertices that have chromatic number 5.',
		868: '868 has a square root whose decimal part starts with the digits 1-9 in some order.',
		869: '869 is the number of different resistances that can be created in a circuit of 9 equal resistors.',
		870: '870 is the sum of its digits and the cube of its digits.',
		872: '872 is a value of n for which n! + 1 is prime.',
		873: '873 = 1! + 2! + 3! + 4! + 5! + 6!',
		874: '874 is the number of positive integer solutions to (1 + 1/a)(1 + 1/b)(1 + 1/c)(1 + 1/d)(1 + 1/e) = 2.',
		875: '875 is 3-automorphic.',
		876: '876 is a dodecagonal pyramidal number.',
		877: '877 is the 7th Bell number.',
		878: '878 is the number of 3×3 sliding puzzle positions that require exactly 29 moves to solve starting with the hole on a side.',
		879: '879 is a number n whose 5th root has a decimal part that begins with the digits of n.',
		880: '880 is the number of 4×4 magic squares.',
		881: '881 is a number n whose 5th root has a decimal part that begins with the digits of n.',
		882: '882 is the smallest number whose square begins with three 7\'s.',
		883: '883 is a number n whose 5th root has a decimal part that begins with the digits of n.',
		884: '884 is a number n whose 5th root has a decimal part that begins with the digits of n.',
		885: '885 is an enneagonal pyramidal number.',
		887: '887 is a value of n for which σ(n) is a repdigit.',
		888: '888 and the following 18 numbers are composite.',
		889: '889 is a Kaprekar constant in base 2.',
		891: '891 is the number of unlabeled distributive lattices with 15 elements.',
		892: '892 is the smallest integer ratio of a 13-digit number to its product of digits.',
		893: '893 has a square whose digits each occur twice.',
		894: '894 has a base 5 representation that begins with its base 9 representation.',
		895: '895 is a Woodall number.',
		896: '896 is not the sum of 4 non-zero squares.',
		897: '897 is a Cullen number.',
		898: '898 is a member of the Fibonacci-type sequence starting with 2 and 5.',
		899: '899 is the product of twin primes.',
		900: '900 has a base 5 representation that begins with its base 9 representation.',
		901: '901 is the sum of the digits of the first 100 positive integers.',
		902: '902 is a value of n so that n(n+7) is a palindrome.',
		903: '903 is the 6th super Catalan number',
		904: '904 has a cube that is the sum of 3 positive cubes.',
		905: '905 is the smallest composite number that is not the sum of a prime and a power of 2.',
		906: '906 is the number of perfect graphs with 7 vertices.',
		907: '907 is the largest n so that Q(√n) has class number 3.',
		909: '909 is a value of n that has has no digits in common with 2n, 3n, 4n, 5n, 6n, 7n, 8n, or 9n.',
		910: '910 is the generalized Catalan number C(11,4).',
		911: '911 is the American emergency number.',
		912: '912 is a Pentanacci number.',
		913: '913 has exactly the same digits in 3 different bases.',
		914: '914 is the number of binary rooted trees with 15 vertices.',
		916: '916 is a strobogrammatic number.',
		917: '917 is the only positive number known whose 9th power can be written as the sum of ten 9th powers.',
		918: '918 is a number that does not have any digits in common with its cube.',
		919: '919 is the smallest number which is not the difference between palindromes.',
		920: '920 is a truncated cube number.',
		922: '922 = 1234 in base 9.',
		923: '923 multiplied by its successor gives a number concatenated with itself.',
		924: '924 is the 6th central binomial coefficient.',
		925: '925 is the number of partitions of 37 in which no part occurs only once.',
		926: '926 is the smallest number that can not be formed using the digits 1-6 at most once, with the operators +, –, ×, ÷, and ^.',
		927: '927 is the 13th tribonacci number.',
		929: '929 is a Proth prime.',
		930: '930 is the number of even permutations on 7 elements with no fixed points.',
		933: '933 is a house number.',
		934: '934 has a 5th root that starts 3.25252225....',
		935: '935 is a Lucas-Carmichael number.',
		936: '936 is a pentagonal pyramidal number.',
		938: '938 is the number of lines passing through at least 2 points of an 8×8 grid of points.',
		939: '939 has a cube root whose decimal part starts with the digits 1-9 in some order.',
		940: '940 is the maximum number of regions space can be divided into by 15 spheres.',
		941: '941 is the smallest number which is the reverse of the sum of its proper substrings.',
		942: '942 is the smallest number whose cube contains five 8\'s.',
		943: '943 is a Lucas 6-step number.',
		945: '945 is the smallest odd abundant number.',
		946: '946 is a hexagonal pyramidal number.',
		948: '948 is the number of symmetric plane partitions of 24.',
		949: '949 is the larger number in a Ruth-Aaron pair.',
		950: '950 is the generalized Catalan number C(17,3).',
		951: '951 is the number of functions from 8 unlabeled points to themselves.',
		952: '952 = 93 + 53 + 23 + 9 × 5 × 2.',
		953: '953 is the largest prime factor of 54321.',
		955: '955 is the number of ways to to arrange the numbers 1-9 around a circle so that the sums of adjacent numbers are distinct.',
		956: '956 is the number of multigraphs with 16 vertices and 4 edges.',
		957: '957 is a value of n for which σ(n) = σ(n+1).',
		958: '958 is the number of labeled 3-colorable graphs with 5 vertices.',
		959: '959 is a Carol number.',
		960: '960 is the sum of its digits and the cube of its digits.',
		961: '961 is a square whose digits can be rotated to give another square.',
		963: '963 is a value of n for which π(n) is the product of the digits of n.',
		964: '964 is the number of 3×3 sliding puzzle positions that require exactly 12 moves to solve starting with the hole in the center.',
		966: '966 is the Stirling number of the second kind S(8,3).',
		967: '967 is the number of 6-digit triangular numbers.',
		968: '968 is an Achilles number.',
		969: '969 is a tetrahedral palindrome.',
		970: '970 is the number of connected graphs with 8 vertices and 17 edges.',
		972: '972 is an Achilles number.',
		973: '973 is the number of inequivalent asymmetric Ferrers graphs with 25 points.',
		974: '974 is the number of multigraphs with 5 vertices and 10 edges.',
		975: '975 is the number of 11-ominoes that contain 1 hole.',
		976: '976 has a square formed by inserting a block of digits inside itself.',
		977: '977 is a Stern prime.',
		978: '978 24 + 34 + 44 + 54.',
		979: '979 is the sum of the first five 4th powers.',
		980: '980 is the number of trees on 23 vertices with diameter 4.',
		981: '981 is the smallest number that has 5 different partitions into 3 parts with the same product.',
		982: '982 is the number of partitions of 39 into distinct parts.',
		983: '983 is a Wedderburn-Etherington number.',
		984: '984 = 8 + 88 + 888.',
		985: '985 is the 9th Pell number.',
		986: '986 is a strobogrammatic number.',
		987: '987 is the 16th Fibonacci number.',
		988: '988 is the maximum number of regions a cube can be cut into with 18 cuts.',
		989: '989 is the smallest number so that it and its reverse are divisible by 43.',
		990: '990 is a triangular number that is the product of 3 consecutive integers.',
		991: '991 is a permutable prime.',
		992: '992 is the number of differential structures on the 11-dimensional hypersphere.',
		993: '993 is the number of paraffins with 8 carbon atoms.',
		994: '994 is the smallest number with the property that its first 18 multiples contain the digit 9.',
		995: '995 has a square formed by inserting a block of digits inside itself.',
		996: '996 has a square formed by inserting a block of digits inside itself.',
		997: '997 has a cube root that starts 9.98998998....',
		998: '998 is the smallest number with the property that its first 55 multiples contain the digit 9.',
		999: '999 is a Kaprekar number.',
		1000: '1000 = 10^3.',
		1001: '1001 is the smallest palindromic product of 3 consecutive primes.',
}

exports.year = {
		129: 'Emperor Hadrian continues his voyages, now inspecting Caria, Cappadocia and Syria',
		130: 'Claudius Ptolemaeus tabulates angles of refraction for several media',
		131: 'Emperor Hadrian builds the city Aelia Capitolina on the location of Jerusalem',
		132: 'Chinese scientist Zhang Heng invents the first seismometer for determining the exact cardinal direction of earthquakes hundreds of miles away',
		133: 'Sextus Julius Severus, governor of Britain, is sent to Judea (from 136 renamed Syria Palaestina) to quell a revolt',
		134: 'a university of rhetoric, law and philosophy, the Athenaeum, opens in Rome',
		135: 'Epictetus writes the Enchiridion (approximate date)',
		136: 'The war against the Suebi begins',
		137: 'Wang Yun, Chinese Prime Minister, plotted Dong Zhuo\'s assassination and was successful',
		138: 'the silver content of the Roman denarius falls to 75 percent under emperor Antoninus Pius, down from 87 percent under the reign of Hadrian',
		139: 'Marcus Aurelius is named Caesar. He marries Faustina the Younger, daughter of Antoninus Pius',
		140: 'Ptolemy completes his Almagest (approximate date)',
		162: 'Parthian War with Rome begins',
		163: 'Statius Priscus reconquers Armenia; Artaxata is ruined',
		164: 'In Rome, a law is passed protecting property brought into a marriage by the wife',
		165: 'Dura-Europos is taken by the Romans',
		166: 'Dacia is invaded by barbarians',
		167: 'The Germans devastate the Balkans and ransack the sanctuary of Eleusis, near Athens',
		168: 'Emperor Marcus Aurelius and his stepbrother Lucius Verus leave Rome, and establish their headquarters at Aquileia',
		169: 'Lucian demonstrates the absurdity of fatalism',
		170: 'The fundamental works of Ptolemy on cartography are published',
		171: 'Armenia and Mesopotamia becomes a protectorate of the Roman Empire',
		172: 'Montanism spreads through the Roman Empire',
		173: 'Given control of the Eastern Empire, Avidius Cassius, the governor of Syria, crushes an insurrection of shepherds known as the boukoloi',
		174: 'Meditations by Marcus Aurelius is written, in Greek, while on military campaigns',
		175: 'Confucian scholars try to ensure their capacity in the royal court of China. They are massacred by the eunuchs',
		176: 'Equestrian Statue of Marcus Aurelius is made. It is now kept at Museo Capitolini in Rome (approximate date)',
		177: 'Second Marcomannic War: Marcus Aurelius and Commodus begin war against the Quadi and the Marcomanni',
		180: 'Galen\'s popular work on hygiene is published',
		181: 'The volcano associated with Lake Taupo in New Zealand erupts, one of the largest on Earth in the last 5,000 years. The effects of this eruption are seen as far away as Rome and China',
		182: 'Emperor Commodus escapes death at the hands of assassins, who have attacked him at the instigation of his sister Lucilla and a large group of senators. He puts many distinguished Romans to death on charges of being implicated in the conspiracy, Lucilla is exiled to Capri',
		184: 'the Yellow Turban Rebellion and Liang Province Rebellion break out in China',
		185: 'a supernova now known as SN 185 is noted by Chinese astronomers in the Astrological Annals of the Houhanshu, making it the earliest recorded supernova',
		186: 'the Hatepe volcanic eruption extends Lake Taupo and makes skies red across the world',
		187: 'Clodius Albinus defeats the Chatti, a highly organized German tribe that controlled the area that includes the Black Forest',
		188: 'Queen Himiko (aka, Pimiko) is said to have begun her reign in Japan',
		189: 'Galen publishes his "Treatise on the various temperaments" (aka On the Elements According to Hippocrates)',
		190: 'Cleomedes teaches that the moon does not glow on its own, but rather reflects sunlight',
		191: 'Chinese warlords formes a coalition force and launches a punitive campaign against Chancellor Dong Zhuo. He forced Emperor Xian to move to Chang\'an (modern Xi\'an) and burns the capital Luoyang',
		192: 'December 31 – Emperor Commodus alarms the Senate by appearing dressed as a gladiator for his new consulship (January 1). His mistress, Marcia, finds her name on the imperial execution list and hires the champion wrestler named Narcissus to assassinate Commodus. The Antonines dynasty ends',
		193: 'The silver content of the Roman denarius falls to 50 percent under emperor Septimius Severus, down from 68 percent under Marcus Aurelius',
		194: 'Galen writes his manual on pathology, The Art of Curing',
		195: 'Emperor Septimius Severus has the Senate deify Commodus in an attempt to gain favor with the family of Marcus Aurelius',
		196: 'Emperor Septimius Severus captures and sacks Byzantium, the city is rebuilt and regains its previous prosperity',
		197: 'Galen\'s major work on medicines, Pharmacologia, is published',
		198: 'Publius Septimius Geta, son of Septimus Severus, receives the title of Caesar',
		199: 'Emperor Septimius Severus lays siege to the city-state Hatra in Central-Mesopotamia, but fails to capture the city despite breaching the walls',
		200: 'human population reaches about 257 million',
		201: 'Osroene becomes the first state which adopts Christianity as its official religion (per New International Encyclopedia)',
		202: 'Rome establishes medical licenses, awarded only to trained physicians who have passed examinations. Medical societies and civic hospitals are set up, and laws are passed to govern the behavior of medical students. They are prohibited from visiting brothels',
		203: 'Emperor Septimius Severus rebuilds Byzantium.',
		204: 'A trade recession in the Leptis Magna region (Africa) is alleviated by emperor Septimius Severus, he buys up the country\'s olive oil for free distribution in Rome.',
		205: 'Hadrian\'s Wall is restored, after heavy raids by Caledonian tribes had overrun much of northern Britain',
		207: 'Cao Cao defeats the Wuhuan tribes at the Battle of White Wolf Mountain, sending the Wuhuan into decline',
		208: 'Emperor Septimius Severus leads an expedition (20,000 men) in Britannia, crosses Hadrian\'s Wall and moves through eastern Scotland. The Roman army pushes the Caledonians back to the River Tay and Severus signs a peace treaty. He repairs the Antonine Wall (his repairs are sometimes called the Severan Wall)',
		209: 'Severus makes plans to subdue the land to the north of Scotland, ravaging it severely. Road-building and forest-clearing, the Roman army reaches Aberdeen. The Scottish tribes begin guerrilla warfare against the Romans',
		210: 'Having suffered heavy losses since invading Scotland in 208, emperor Septimius Severus makes peace with the Scots',
		211: 'Emperor Septimius Severus falls ill and dies in Britain after an 18-year reign. He is later deified by the Senate',
		212: 'The edict of emperor Caracalla (Constitutio Antoniniana) extends Roman citizenship to all free inhabitants of the Roman Empire with the exception of a limited group that may include Egyptians. The Jewish people are among those who receive citizenship',
		213: 'Cao Cao, the prime minister of the Han dynasty, is titled Wei Gong (Duke of Wei) and given a fief of ten cities under his domain. This later becomes the Kingdom of Wei',
		214: 'Caracalla\'s victories in Germany ensure his popularity within the Roman army.',
		215: 'Caracalla\'s troops massacre the population of Alexandria, Egypt, beginning with the leading citizens. The emperor is angry about a satire, produced in Alexandria, mocking his claim that he killed Geta in self-defense.',
		216: 'Emperor Caracalla tricks the Parthians by accepting a marriage proposal. He slaughters his bride and the wedding guests after the celebrations',
		217: 'Summer – Battle of Nisibis: The Roman army under command of Macrinus, is defeated in a three days battle by the Parthians at Nisibis (southern Turkey)',
		218: 'May 16 – Julia Maesa, an aunt of the assassinated Caracalla, is banished to her home in Syria by the self-proclaimed emperor Macrinus and declares her grandson Elagabalus, age 14, emperor of Rome',
		219: 'Julia Maesa arranges for her grandson Elagabalus a marriage with Julia Paula. The wedding is a lavish ceremony and Paula is given the honorific title of Augusta',
		220: 'Elagabalus divorces Julia Paula and marries Aquilia Severa, a Vestal Virgin. The wedding causes a enormous controversy – traditionally, the punishment for breaking celibacy is death by being buried alive',
		221: 'July – Elagabalus is forced to divorce Aquilia Severa and marries his third wife Annia Faustina. After five months he returns to Severa and claims that the original divorce is invalid. The marriage is symbolic, because Elagabalus appears to be homosexual or bisexual. According to the historian Cassius Dio, he has a stable relationship with his chariot driver, the slave Hierocles',
		222: 'Three Kingdoms: Eastern Wu is established in China. Emperor Liu Bei invades with a army (100,000 men) the border of Eastern Wu in the Battle of Yiling to retake the Jing province. However, because of a tactical mistake, Liu Bei\'s military camps are destroyed by forces of Sun Quan.',
		223: 'Three Kingdoms: Emperor Liu Bei of the Shu Han becomes ill and dies at Baidicheng. He is succeeded by his son, Liu Shan. Imperial Chancellor, Zhuge Liang, makes peace with the Wu Empire',
		224: 'King Ardashir I defeats Artabanus IV at Hormizdegan (modern Shushtar), destroying the Parthian Empire and establishing the Sassanid dynasty. Artabanus\'s brother Vologases VI will continue to rule with Armenian and Kushan support over outlying parts of Parthia.',
		225: 'Emperor Alexander Severus marries Sallustia Orbiana, and possibly raises her father Seius Sallustius to the rank of caesar',
		226: 'A merchant from the Roman Empire called "Qin Lun" by the Chinese, arrives in Jiaozhi (modern Hanoi) and is taken to see Sun Quan, king of Eastern Wu, who requests him to make a report on his native country and people. He is given an escort for the return trip including a present of ten male and ten female "blackish-coloured dwarfs." However, the officer in charge of the Chinese escort dies and Qin Lun has to continue his journey home alone',
		227: 'Seius Sallustius is executed for the attempted murder of his son-in-law Emperor Alexander Severus. Sallustius\' daughter, as well Alexander\'s wife, Sallustia Orbiana, is exiled in Libya',
		228: 'The Praetorian Guard kill Ulpian, Praetorian prefect, who had wanted to reduce their privileges',
		229: 'Ammonius Saccas renews Greek philosophy by creating Neoplatonism',
		230: 'Alexander Severus assembled the Roman army and establish his headquarters at Antioch. He makes an attempt for diplomatic solutions, but the Persians decline and choose for war',
		231: 'Emperor Alexander Severus accompanied his mother Julia Mamaea to Syria and campaigns against the Persians. Military command rests in the hands of his generals, but his presence gives additional weight to the empire\'s policy.',
		232: 'Roman–Persian Wars: Emperor Alexander Severus launches a three-pronged counterattack against the Persian forces of king Ardashir I, who have invaded Mesopotamia. However, the Roman army advancing through Armenia is halted. Alexander gives the order to march to the capital at Ctesiphon, but the Romans are defeated and withdraw to Syria. The result is a acceptance of the status quo and after heavy losses on both sides, a truce is signed',
		233: 'Emperor Alexander Severus celebrates a triumph in Rome to observe his "victory" the previous year over the Persians. He is soon summoned to the Rhine frontier, where the Alamanni invade Swabia. German tribes destroy Roman forts and plunder the countryside at the Limes Germanicus',
		234: 'Zhuge Liang, Chancellor of Shu Han, embarks on his last Northern Expedition against Cao Wei. During the Battle of Wuzhang Plains, he falls sick and sends secret orders for his army to retreat',
		235: 'March 20 – Maximinus Thrax, age 62, is proclaimed emperor. He has a Gothic father and an Alan mother. Maximinus a Thracian, is the first foreigner to hold the Roman throne',
		236: 'The Roman Senate appoints a twenty-man committee to co-ordinate operations against Maximinus',
		237: 'Emperor Maximinus Thrax campaigns on the rivers Danube and Rhine in Germania, defeating the Alemanni and never visits Rome. He is accepted by the Roman Senate, but taxes the rich aristocracy heavily and engenders such hostility among them that they plot against him',
		238: 'July 29 – The Praetorian Guard stormed the palace and capture Pupienus and Balbinus. They are dragged naked through the streets of Rome and executed. On the same day Gordian III, age 13, is proclaimed new emperor. Timesitheus becomes his tutor and advisor',
		239: 'A Chinese expeditionary force discovers the island of Taiwan',
		240: 'The Roman Empire is threatned on several fronts at the same time. Africa revolts and tribes in northwest Germania, under the name of the Franks, are raiding the Rhine frontier',
		241: 'Winter – Emperor Gordian III reaches Antioch and prepares with his army an offensive against the Persians',
		242: 'Emperor Gordian III begins a campaign against king Shapur I, the Greek philosopher Plotinus joins him and hopes to obtain first-hand knowledge of Persian and Indian philosophies',
		243: 'Timesitheus becomes ill and dies under suspicious circumstances. Shapur I retreats to Persia, giving up all the territories he conquered',
		244: 'Plotinus, Greek philosopher, escapes the bloodshed that accompanies the murder of Gordianus III and makes his way to Antioch. Back to Rome he founds his Neoplatonist school and attracts students like Porphyry, Castricius Firmus and Eustochius of Alexandria',
		245: 'Trieu Thi Trinh, a Vietnamese warrior, begins her three year resistance against the invading Chinese',
		246: 'Emperor Philip the Arab fights the Germans along the Danube',
		247: 'the Goths appear on the lower Danube frontier, they invade the Ukraine and Romania',
		248: 'The Roman Empire continues the celebration of the 1,000th anniversary of the city of Rome, with the ludi saeculares, organized by Philip the Arab',
		249: 'Trajan Decius puts down a revolt in Moesia and Pannonia. Loyal legionaries proclaim him emperor and he leads them into Italy. At a battle at Verona, he defeats and kills Philip the Arab',
		250: 'Diophantus writes Arithmetica, the first systematic treatise on algebra',
		251: 'A fifteen-year plague begins in the Roman Empire',
		252: 'Valerian reforms Legio III Augusta to fight the "five peoples", a dangerous coalition of Berber tribes in Africa',
		253: 'Battle of Barbalissos: King Shapur I, defeats the Roman army (70,000 men) under Valerianus I at Barbalissos in Syria',
		254: 'Publius Licinius Valerianus Augustus and Publius Licinius Egnatius Gallienus become Roman Consuls.',
		255: 'Ma Jun, a Chinese mechanical engineer from Cao Wei, invents the South Pointing Chariot, a path-finding directional compass vehicle that uses a differential gear, not magnetics',
		256: 'the great pandemic of the Roman world strikes violently in Pontus on the Black Sea and causes enormous loss of life in Alexandria, encouraging thousands to embrace Christianity',
		257: 'The Goths separate into the Ostrogoths and the Visigoths',
		258: 'Nanjing University is founded in Nanjing, China',
		259: 'Emperor Valerian leads an army (70,000 men) to relieve Edessa, besieged by the forces of king Shapur I. An outbreak of a plague kills many legionaries, weakening the Roman position in Syria',
		260: 'Earliest known date of chess',
		261: 'Roman-Persian Wars: Balista, Roman usurper, collects ships from Cilician ports and defeats the Persian fleet near Pompeiopolis, capturing the harem of king Shapur I',
		262: 'The Heruls accompanied the Goths ravaging the coasts of the Black Sea and the Aegean',
		263: 'Liu Hui writes a commentary on The Nine Chapters on the Mathematical Art, describing what will later be called Gaussian elimination, computing pi, etc.',
		264: 'Jiang Wei tries to restore the Kingdom of Shu by persuading Zhong Hui to declare a rebellion against Sima Zhao, ruler of Cao Wei. They receive no support from the Wei troops, and Zhong Hui, Jiang Wei and their families are put to death',
		265: 'Jin Wudi becomes ruler of part of China, beginning the Jin Dynasty. He establishes his capital at Luoyang and gives princes of his uncles, cousins, brothers, and sons, independent military commands in the Chinese Empire',
		266: 'King Odaenathus of Palmyra invades Persia to conquer the capital Ctesiphon. After his victories in the East he pronouns himself with the title "king of kings"',
		267: 'Aureolus, charged with defending Italy, defeats Victorinus (co-emperor of Gaul), is proclaimed emperor by his troops, and begins his march on Rome',
		268: 'Gallienus is killed by his own senior officers at Mediolanum (Milan) while besieging his rival Aureolus, one of the Thirty Tyrants. Aureolus is murdered in turn by the Praetorian guard',
		269: 'The Heruli capture Athens and raid the Aegean Islands as far as Crete and Rhodes',
		270: 'The Chinese invent gunpowder (black powder), a mixture of sulfur, charcoal and potassium nitrate. At first, it appears to have been used only for fireworks',
		271: 'A magnetic compass is first used in China',
		272: 'During the Siege of Tyana, Emperor Aurelian has a dream of Apollonius of Tyana and spares the city',
		273: 'Aurelian increases Rome\'s daily bread ration to nearly 1.5 pounds and adds pig fat to the list of foods distributed free to the populace',
		274: 'Japanese shipwrights build a 100-foot oar-powered vessel for Emperor Ōjin. The Japanese will not use sails for another 7 centuries',
		275: 'September 25 – Marcus Claudius Tacitus is proclaimed Emperor by the Senate, his half brother Marcus Annius Florianus becomes Praetorian Prefect',
		276: 'Reign of Mahasena in Ceylon. Orthodox and unpopular, he tries to introduce Mahayana Buddhism to the country',
		277: 'Probus enters Rome to have his position as Emperor ratified by the Senate',
		278: 'Piracy along the coast of Lycia and Pamphylia. The Romans besiege the city of Cremna (Pisidia) and killed the Isaurian robber Lydius',
		279: 'Emperor Probus defeats the Burgundians and Vandals in Raetia and Pannonia (modern Switzerland and Hungary)',
		280: 'The Greek mathematician Pappus demonstrates geometrically the property of the center of gravity',
		281: 'Emperor Probus returns to Rome, where he celebrates his triumph over the Vandals and the usurpers (Bonosus, Julius Saturninus and Proculus)',
		282: 'Emperor Probus travels towards Sirmium (Serbia). He tries to employ his troops in peaceful projects as draining the swamps in Pannonia',
		283: 'Carus dies in mysterious circumstances during an expedition against the Sassanids, during a violent dust storm he is killed by a stroke of lightning',
		284: 'Gaius Aurelius Valerius Diocletianus, age 39, is proclaimed new emperor. He establish himself at Nicomedia (modern İzmit, Turkey) and accepts the purple imperial vestments',
		285: 'Carausius, naval commander at Bononia (modern Boulogne), is given the task to clear the English Channel of Frankish and Saxon pirates',
		286: 'Diocletian divides the empire in two, after economic and military problems. He gives Maximian control over the Western Roman Empire and appoints himself ruler of the Eastern Roman Empire (later known as the Byzantine Empire)',
		287: 'Diocletian re-organized the Mesopotamian frontier and fortifies the city of Circesium (modern Busayrah) on the Euphrates',
		288: 'Emperor Diocletian conducts a military campaign in Raetia (Switzerland)',
		289: 'Maximian attempts to reconquer Britain from the usurper Carausius, but fails due to bad weather. He loses his fleet and accepts a peace treaty',
		290: 'Carausius begins to build a series of fortifications on the Saxon Shore in south-east England',
		291: 'Emperor Diocletian signs peace treaties with the kingdoms of Aksum and Nubia',
		292: 'Achilleus, Roman general, is proclaimed emperor in Alexandria. For two years he rules over Egypt, but in the end the rebellion is crushed by Emperor Diocletian',
		293: 'King Bahram II of the Persian Empire dies after a 17-year reign, his son Bahram III ascends to the throne. After four months he is murdered by viceroy Narseh with support of the nobility',
		294: 'Galerius is given the unspectacular job of land reclamation and repopulation, moving the entire tribe of the Carpi to settlements within the Roman Empire',
		295: 'Galerius, Roman Caesar in the Balkan, is dispatched to Egypt to fight against the rebellious cities Busiris and Coptos',
		296: 'Constantius Chlorus reconquers Britain, he rebuilds the cities Eboracum (York), Londinium (London), and Verulamium (St Albans)',
		297: 'Emperor Maximian begins a offensive against the Berbers in Mauritania, driving them back into their homelands in the Atlas Mountains. He spends the rest of the winter in Carthage (Africa)',
		298: 'The manufacture of cultured silk becomes popular from Korea to Japan',
		299: 'Galerius commissions the Arch of Galerius in Thessaloniki (Greece). The structure is built to celebrate the war and victory over the Sassanid Persians',
		300: 'The elephant becomes extinct in North Africa (approximate date)',
}

exports.trivia = {
		114: 'the number of chapters in the Quran',
		120: 'liters of water needed to produce 1 glass of wine',
		125: 'years in a quasquicentennial',
		137: 'the average brain mass of a baboon in grams',
		139: 'the number of unlabeled topologies with 5 elements',
		140: 'liters of water needed to produce 1 cup of coffee',
		142: 'the number of 6-vertex planar graphs',
		144: 'a gross (a dozen dozen)',
		150: 'years in a sesquicentennial',
		151: 'total number of types of Pokémon in the original set',
		156: 'the number of strikes a clock will strike in the course of a day',
		159: 'the number of isomers of C11H24',
		160: 'the number of characters permitted in a standard short message service in Australia and Europe',
		161: 'the number of songs Pink Floyd recorded',
		162: 'total number of baseball games each team plays during a regular season in Major League Baseball',
		164: 'the number of home runs the Baltimore Orioles hit in 2006',
		166: 'the number of Warner Bros. cartoons Bugs Bunny starred in from 1940 to 1964',
		167: 'the number of tennis titles Martina Navratilova has, an all-time record for men or women',
		168: 'hours in a week',
		169: 'the number of nonequivalent starting hands in the Texas hold \'em',
		170: 'largest integer for which Google\'s built-in calculator function can compute the factorial',
		173: 'years it takes for all the water in Lake Superior to be changed',
		174: 'the number of miles the Columbia University Library System collection, with over 9.3 million volumes, would stretch end-to-end',
		175: 'years Harriet (1830–2006) the Galápagos tortoise lived ',
		180: 'the standard number of days in the school year in most areas of the USA',
		186: 'days between the spring and fall equinoxes',
		189: 'the number of irregular verbs in the English language (from "abide" to "write")',
		193: 'species of monkeys and apes',
		196: 'the length of the Adda River in Italy',
		199: 'steps to the top of the Cape May Lighthouse in Cape May, New Jersey',
		200: 'degrees in a human\'s field of vision (approximately)',
		206: 'bones in the typical adult human body',
		208: 'the heaviest stable isotope of any element (lead)',
		212: 'the boiling point of water at sea level in Fahrenheit degrees',
		214: 'the number of Chinese radicals for the writing of Chinese characters according to the 1716 Kangxi Dictionary',
		216: 'the number of stitches on a baseball, according to the Ken Burns series "Baseball"',
		218: 'votes required in the US House of Representatives to achieve a majority as of 2008',
		222: 'the score in the 1916 Cumberland vs. Georgia Tech football game, with Georgia Tech winning 222-0, which was the record for most points scored by one team in an American football game',
		227: 'the number of days Pi Patel was at sea in the popular novel, Life of Pi',
		229: 'the lowest individual batting score not achieved by any player in test match cricket',
		231: 'the number of cubic inches in a U.S. liquid gallon',
		240: 'distinct solutions of the Soma cube puzzle',
		243: 'the number of Earth Days for the planet Venus to complete one Venetian day, one revolution',
		245: 'the number of Jewish singers who returned from captivity in Babylon in circa 538 BCE BC following the rise of Cyrus the Great and the Persian Empire',
		248: 'the number of organs in the human body as traditionally depicted',
		250: 'the number of Pokémon originally available in Pokémon Gold and Silver before Celebi was added',
		255: 'the largest representable integer in an unsigned byte',
		256: 'the number of NFL regular season football games',
		261: 'number of possible unfolded tesseract patterns',
		267: 'the number of groups of order 64',
		270: 'the average number of days in human pregnancy',
		273: 'the death toll of the air crash of American Airlines Flight 191',
		276: 'the highest number of rounds in boxing history, in a bare-knuckle fight in 1825 that saw Jack Jones beat Patsy Tunney after 4hr 30min',
		285: 'the total number of Rules of Acquisition in Star Trek',
		295: 'the numerical designation of seven circumfrental or half-circumfrental routes of Interstate 95 in the United States',
		300: 'a perfect score in bowling, achieved by rolling strikes in all ten frames (a total of twelve strikes)',
}
